## Stages by grouping
shared:
  image: node:14
  steps:
    - init: echo 'init'
jobs:
  triggering-stage:
    requires: [~pr, ~commit]
  ci-deploy:
    requires: [ ~stage@integration:setup ]
  ci-test:
    requires: [ ci-deploy ]
  ci-certify:
    requires: [ ci-test ]
  triggered-by-stage:
    requires: [ ~stage@integration:teardown ]

stages:
  integration:
    requires: [triggering-stage]
    jobs: [ci-deploy, ci-test, ci-certify]
    description: "testP PR"
